### ISSUE TITLE
CircleBattery icon color not automatic  change

### ISSUE THREAD

**Issue by cxyzzz** [GravityBox/GravityBox#1921] opened 2019-03-13 14:16 UTC
I turn on the CircleBattery icon ,but the icon color not automatic change,it's Always white ,The battery icon will not be visible when the status bar background is white.

Android version:9.0
OS: mokee 90
Magisk version:v18.2-b3140276 (18101)
riru-core version:v17
Riru - Ed Xposed version:v0.3.1.2_beta

thans for your work!

**Comment by C3C0** [comment] 2019-03-13 14:45
This is caused by incompatibility with Mokee which is not officially supported. I cannot adjust functioanltiy without physically working with such system.

**Comment by C3C0** [comment] 2019-03-14 08:52
Should be fixed in e42e6f3ef39f9d2eb3c2d4ab301c40dbd335e2f9

**Closed as completed by C3C0** 2019-03-14 08:52 UTC

**Comment by cxyzzz** [comment] 2019-03-17 05:25
> Should be fixed in [e42e6f3](https://github.com/GravityBox/GravityBox/commit/e42e6f3ef39f9d2eb3c2d4ab301c40dbd335e2f9)

It work ,thanks!
