### ISSUE TITLE
[BUG] Alarm icon always showing after beta 9

### ISSUE THREAD

**Issue by GrPK** [GravityBox/GravityBox#1972] opened 2019-04-29 12:48 UTC
Hello. I'm using Samsung Note 9, latest gravitybox,edxposed,riru etc. After beta 9 update, the alarm icon is always showing, even if I didnt have any alarm. Before, it worked as expected. I attached some logs here. Hope it helps
[2019-04-29_15.42.zip](https://github.com/GravityBox/GravityBox/files/3127415/2019-04-29_15.42.zip)
Added screenshot to prove it.
![Screenshot_20190607-103758_Clock](https://user-images.githubusercontent.com/31523635/59088597-9db6dd80-8910-11e9-9586-5d683a8f2fb4.jpg)

**Comment by C3C0** [comment] 2019-04-29 12:56
There weren't any changes between beta-8 and 9 regarding that functionality.

**Comment by Firefds** [comment] 2019-04-29 13:35
I can't reproduce this on the S8. No alarm icon is showing when no alarm is set.
Also hide alarm options works correctly.

**Comment by GrPK** [comment] 2019-04-29 22:28
Tried with beta 8, No issues. So I think it is something regarding with latest status bar update?

**Comment by C3C0** [comment] 2019-04-30 06:03
Although it doesn't make sense to me, try disabling "Max notification icons" feature in status bar tweaks to see whether it makes any difference (I recommend rebooting). That's the one and only feature related to status bar that's been introduced in beta-9.

**Comment by GrPK** [comment] 2019-05-20 20:22
Found a fix!
For the ones that have GooldLock: Delete QuickStar then delete Gravitybox
Reboot
Reinstall quickstar
Reboot
Reinstall gravitybox (do not activate)
Reboot
Activate gravitybox
Reboot
Profit!

**Comment by GrPK** [comment] 2019-06-07 07:36
Re-open because the issue is still present.

**Comment by C3C0** [comment] 2019-06-07 08:43
Please test with attached APK and report back.
[GravityBox-Pie-9.0.0-beta-11-test1.apk.zip](https://github.com/GravityBox/GravityBox/files/3265141/GravityBox-Pie-9.0.0-beta-11-test1.apk.zip)

**Comment by GrPK** [comment] 2019-06-07 23:06
It fixed it!
Thanks a lot a lot a lot a lot!

**Comment by GrPK** [comment] 2019-06-07 23:12
Hope you push the fix asap, cant wait to activate pro and configure it (It shows that I have a tempered version, probably cause of "test" version)

**Comment by C3C0** [comment] 2019-06-08 05:42
OK. Thanks for confirming. It will take some time for new version to be released as I still need to implement couple of OnePlus 7Pro compatibility improvements. But I added your test build to the list of official releases on the server so you should be able to use unlock code on it.

**Closed as completed** 2024-10-06 00:03 UTC
